name: CD (Publish Docker images)

on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types: [completed]

jobs:
  docker-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build + push check-ip
        run: |
          SHA=${{ github.event.workflow_run.head_sha }}
          docker buildx build \
            --target check-ip \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/check-ip:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/check-ip:${{ github.sha }} \
            --push .

      - name: Build + push check-ip-batch
        run: |
          SHA=${{ github.event.workflow_run.head_sha }}
          docker buildx build \
            --target check-ip-batch \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/check-ip-batch:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/check-ip-batch:${{ github.sha }} \
            --push .
