name: CD (Publish Docker images)

on:
  push:
    branches: ["main"]

jobs:
  docker-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build + push check-ip
        run: |
          docker buildx build \
            --target check-ip \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/check-ip:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/check-ip:${{ github.sha }} \
            --push .

      - name: Build + push check-ip-batch
        run: |
          docker buildx build \
            --target check-ip-batch \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/check-ip-batch:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/check-ip-batch:${{ github.sha }} \
            --push .
